name: CI
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: 'python-version'
      - name: Install Python dependencies
        run: |
          pip install -U setuptools wheel pip
          pip install -r requirements/main.txt
          pip install -r requirements/dev.txt
          pip check
      - name: Run Tests
        run: |
          pytest
